# Generated by Django 4.2 on 2023-10-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_pages', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
          state_operations=[
                migrations.DeleteModel(
                    name='Wishlist',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Wishlist',
                    table='wishlist_wishlist',
                ),
            ],
        )

    ]
