# Generated by Django 4.2 on 2023-10-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_pages', '0002_delete_wishlist'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CurrentCart',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='CurrentCart',
                    table='cart_currentcart',
                ),
            ],
       )
     ]