# Generated by Django 4.2 on 2023-10-10 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_pages', '0003_delete_currentcart'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Orders',
                ),
            ],
           database_operations=[
                migrations.AlterModelTable(
                    name='Orders',
                    table='orders_orders',
                ),
            ],
        )
     ]
